### ISSUE TITLE
Plugin imports well but has problems exporting

### ISSUE THREAD

**Issue by Guartis** [phonon/blender-vintagestory-json#6]
Error Message:

> Python: Traceback (most recent call last):
>   File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\addons\blender-vintagestory-json-master\io_scene_vintagestory_json\__init__.py", line 268, in execute
>     result = export_vintagestory_json.save(context, **args)
>   File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\addons\blender-vintagestory-json-master\io_scene_vintagestory_json\export_vintagestory_json.py", line 1861, in save
>     save_objects(filepath, objects, **kwargs)
>   File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\addons\blender-vintagestory-json-master\io_scene_vintagestory_json\export_vintagestory_json.py", line 1657, in save_objects
>     element = generate_element(
>   File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\addons\blender-vintagestory-json-master\io_scene_vintagestory_json\export_vintagestory_json.py", line 637, in generate_element
>     face_material = get_face_material(obj, face.material_index)
>   File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\addons\blender-vintagestory-json-master\io_scene_vintagestory_json\export_vintagestory_json.py", line 321, in get_face_material
>     name=material.name,
> UnboundLocalError: local variable 'material' referenced before assignment

**Comment by sekelsta** [comment]
This seems to happen for shapes without included texture info. For a workaround, you can manually set a material for each box in blender before exporting.
